config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "users#index"
    resources :users
    resources :categories do
      resources :questions
    end
    resources :exams
  end

  root "static_pages#home"
  devise_for :users, path: "", path_names: {
    sign_in: "login",
    sign_out: "logout"
  }
  resources :users, only: [:show, :edit, :update]
  resources :exams, only: [:index, :show, :create, :update]

end

app/models/exam.rb
class Exam < ActiveRecord::Base  

  before_create {self.status = Settings.exams.start}
  before_create :create_answer_sheets
  before_update {self.status = Settings.exams.view}
  after_update :send_result_exam

  has_many :answer_sheets
  belongs_to :user
  belongs_to :category

  accepts_nested_attributes_for :answer_sheets, allow_destroy: true
  scope :order_desc, ->{order created_at: :desc}

  def time_remaining
    Settings.exams.minutes*60 - (Time.zone.now - self.created_at).to_i
  end

  def answer_correct
    self.answer_sheets.select{|answer_sheet| !answer_sheet.answer.nil? && 
      answer_sheet.answer.status}.length
  end

  def send_result_exam 
    SendResultExam.perform_async self.id if self.checked
  end

  private
  def create_answer_sheets
    Category.find(self.category_id).questions.
      order("RANDOM()").limit(Settings.questions_per_exam).each do |question|
        self.answer_sheets.build question_id: question.id
    end
  end
end

app/controllers/admin/exams_controller.rb
class Admin::ExamsController < ApplicationController
  load_and_authorize_resource

  def index
    @exams = Exam.all
  end

  def update
    if @exam.update exam_param
      flash[:success] = t "admin.exam.checked_success"
    else
      flash[:danger] = t "admin.exam.checked_failed"
    end
    respond_to do |format|
      format.html {redirect_to admin_exams_path}
      format.js
    end
  end

  def destroy  
    if @exam.destroy
      flash[:success] = t "admin.exams.destroy_success"
    else
      flash[:danger] = t "admin.exams.destroy_failed"
    end
    respond_to do |format|
      format.html {redirect_to admin_exams_path}
      format.js
    end
  end

  private
  def exam_param
    params.require(:exam).permit :checked
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  load_and_authorize_resource

  def index
    @exams = current_user.exams.order_desc.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def create
    @exam = current_user.exams.build exam_params
    if @exam.save
      flash[:success] = t "exams.success_create"
    else
      flash[:danger] = t "exams.danger_create"
    end
    redirect_to exams_path
  end

  def show
    @time_remaining = @exam.time_remaining
    @is_time_over = @time_remaining < 0
    @answer_sheets = Exam.find(params[:id]).answer_sheets
    @answer_correct = @exam.answer_correct
  end

  def update
    if @exam.update_attributes exam_params
      flash[:success] = t "exams.success_update"
    else
      flash[:danger] = t "exams.danger_update"
    end
    redirect_to exam_path @exam
  end

  private
  def exam_params
    params.require(:exam)
      .permit :category_id, answer_sheets_attributes: [:id, :question_id, :answer_id]
  end
end

app/views/admin/exams/_exam.html.erb
<tr id="exam-<%= exam.id %>">
  <td><%= link_to exam.user.id, exam.user %></td>
  <td><%= exam.user.email %></td>
  <td><%= exam.id %></td>
  <td>
    <%= link_to exam.category.name, exam %>
  </td>
  <td>
    <% if exam.checked? %>
      <%= t "admin.exams.checked" %>
    <% else %>
      <%= form_for [:admin, exam], remote: true do |f| %>
        <%= f.hidden_field :checked, value: !exam.checked %>
        <%= f.submit t("admin.exams.check"), class: "btn btn-primary btn-sm" %>
      <% end %>
    <% end %>
  </td>
  <td><%= link_to t("delete"), admin_exam_path(exam), remote: true, method: :delete,
    data: {confirm: t("confirm_action")} %></td>
</tr>

app/views/admin/exams/destroy.js.erb
$("#exam-<%= @exam.id %>").remove();

app/views/admin/exams/index.html.erb
<h1><%= t"admin.exams.all_exam" %></h1>
<div id="section_admin_user">
  <table id="users_record" class="table table-bordered">
    <tbody>
      <tr>
        <th><%= t "admin.exams.user_id" %></th>
        <th><%= t "admin.exams.user_email" %></th>
        <th><%= t "admin.exams.id" %></th>
        <th><%= t "admin.exams.category" %></th>  
        <th><%= t "admin.exams.checked" %></th>
        <th><%= t "delete" %></th>
      </tr>
      <tr>
        <%= render @exams %>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/exams/update.js.erb
$("#exam-<%= @exam.id %>").replaceWith("<%= escape_javascript(render "exam", exam: @exam) %>");