config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "users#index"
    resources :users
    resources :categories do
      resources :questions
    end
    resources :exams
  end

  root "static_pages#home"
  devise_for :users, path: "", path_names: {
    sign_in: "login",
    sign_out: "logout"
  }
  resources :users, only: [:show, :edit, :update]
  resources :exams, only: [:index, :show, :create, :update]

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  has_many :answers, dependent: :destroy

  accepts_nested_attributes_for :answers, allow_destroy: true,
    reject_if: proc {|answer| answer[:content].blank?}
  
  validates :content, presence: true, uniqueness: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  load_and_authorize_resource 
  load_and_authorize_resource :category

  def new
    4.times {@question.answers.build}
  end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:sucess] = t "admin.question.create_success"
    else
      flash[:danger] = t "admin.question.create_failed"
    end
    respond_to do |format|
      format.html {redirect_to admin_category_path @category}
      format.js
    end
  end

  def show
  end

  def edit
  end

  def update
    if @question.update_attributes question_params
      flash[:sucess] = t "admin.question.update_success"
      redirect_to admin_category_path @category
    else
      render :edit
      flash.now[:danger] = t "admin.question.update_failed"
    end
  end

  def destroy
    if @question.destroy
      flash[:info] = t "admin.question.destroy_success"
    else
      flash[:danger] = t "admin.question.destroy_failed"
    end
    respond_to do |format|
      format.html {redirect_to admin_category_path @category}
      format.js
    end
  end
  
  private
  def question_params
    params.require(:question).permit :content, :category_id, answers_attributes: [:id, :content, :status]
  end
end

app/views/admin/questions/_question.html.erb
<tr id="question-<%= question.id %>">
  <td><%= link_to question.content, admin_category_question_path(category_id: @category.id,
    id: question.id) %></td>
  <td>
    <%= link_to "" , admin_category_question_path(category_id: @category.id, id: question.id), method: :delete,
      data: {confirm: t("confirm_action", action: t("delete"))},
      class: "glyphicon glyphicon-remove" %>
    <%= link_to "", edit_admin_category_question_path(category_id: @category.id, id: question.id),
      class: "glyphicon glyphicon-edit" %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<div class="col-md-4">
  <%= form_for [:admin, @category, @question], class: "form" do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="form-group">
      <%= f.label t "admin.question.question" %>
      <%= f.text_field :content, class: "form-control" %>
    </div>
    <div class="form-group" id="means">
      <div id="answer_list">
        <%= f.fields_for :answers, wrapper: true do |answer_form| %>
          <%= render "shared/error_messages", object: answer_form.object %>
          <div class="row answer-form">
            <div class="col-md-5">
              <%= answer_form.label t "admin.question.answer" %>
              <%= answer_form.text_field :content, required: true, class: "form-control" %>
            </div>
            <div class="col-md-3">
              <%= answer_form.label t "correct" %>
              <%= answer_form.check_box :status, class: "checkbox" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <br>
    <%= f.submit t("done"), class: "btn btn-primary pull-right" %>
  <% end %>
</div>

app/views/admin/questions/new.html.erb
<% provide :title, t("admin.question.create_title") %>
<h1><%= t "admin.question.create_title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category, @question], class: "form" do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="form-group">
        <%= f.label t "admin.question.question" %>
        <%= f.text_field :content, class: "form-control",
          placeholder: t("admin.question.enter_new_question") %>
      </div>
      <%= f.hidden_field :category_id, value: @category.id %>
      <div class="form-group" >
        <div id="answer_list">
          <%= f.fields_for :answers, wrapper: true do |answer_form| %>
            <%= render "shared/error_messages", object: answer_form.object %>
            <div class="row answer-form">
              <div class="col-md-5">
                <%= answer_form.label t "admin.question.answer" %>
                <%= answer_form.text_field :content, required: true, class: "form-control" %>
              </div>
              <div class="col-md-3">
                <%= answer_form.label t "correct" %>
                <%= answer_form.check_box :status, class: "checkbox" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <br>
      <%= f.submit t("done"), class: "btn btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/admin/questions/show.html.erb
<div class="col-md-4">
  <%= form_for [:admin, @category, @question], class: "form" do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="form-group">
      <%= f.label t "admin.question.question" %>
      <%= f.text_field :content, class: "form-control" %>
    </div>
    <div class="form-group" id="means">
      <div id="answer_list">
        <%= f.fields_for :answers, wrapper: true do |answer_form| %>
          <%= render "shared/error_messages", object: answer_form.object %>
          <div class="row answer-form">
            <div class="col-md-5">
              <%= answer_form.label t "admin.question.answer" %>
              <%= answer_form.text_field :content, required: true, class: "form-control" %>
            </div>
            <div class="col-md-3">
              <%= answer_form.label t "correct" %>
              <%= answer_form.check_box :status, class: "checkbox" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <br>
  <% end %>
</div>