config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "users#index"
    resources :users
    resources :categories do
      resources :questions
    end
    resources :exams
  end

  root "static_pages#home"
  devise_for :users, path: "", path_names: {
    sign_in: "login",
    sign_out: "logout"
  }
  resources :users, only: [:show, :edit, :update]
  resources :exams, only: [:index, :show, :create, :update]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :exams, dependent: :destroy
  has_many :questions, dependent: :destroy
  scope :ordered_by_name, -> {order "created_at ASC"}
  validates :name, presence: true, length: {maximum: Settings.maximum_category_name_length},
    uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  load_and_authorize_resource

  def index
    @categories = Category.ordered_by_name.paginate page: params[:page], per_page: Settings.per_page
    @category = Category.new
  end
  
  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "admin.category.create_success"   
    else
      flash[:danger] = t "admin.category.create_failed"
      @categories = Category.ordered_by_name.paginate page: params[:page], per_page: Settings.per_page
    end
    respond_to do |format|
      format.html {redirect_to admin_categories_path}
      format.js
    end
  end

  def show
    @questions = @category.questions
  end

  def edit   
  end

  def update
    if @category.update category_params
      flash[:success] = t "admin.category.update_success"
      redirect_to admin_categories_path
    else
      flash.now[:danger] = t "admin.category.update_failed"
      render :edit
    end
  end
    
  def destroy
    if @category.destroy
      flash[:success] = t "admin.category.destroy_success"     
    else
      flash[:danger] = t "admin.category.destroy_failed"
      redirect_to admin_categories_path
    end
    respond_to do |format|
      format.html {redirect_to admin_categories_path}
      format.js
    end
  end

  private
  def category_params
    params.require(:category).permit :name
  end
end

app/views/admin/categories/_category.html.erb
<tr id="category-<%= category.id %>">
  <td><%= link_to category.name, admin_category_path(category) %></td>
  <td><%= category.questions.length %></td>
  <td>
    <%= link_to "", admin_category_path(category), method: :delete, remote: true,
      data: {confirm: t("confirm_action", action: t("delete"))},
      class: "glyphicon glyphicon-remove" %>
    <%= link_to "", edit_admin_category_path(category),
      class: "glyphicon glyphicon-edit" %>
  </td>
</tr>

app/views/admin/categories/create.js.erb
$("table>tbody").
  append("<%= escape_javascript(render('admin/categories/category', category: @category)) %>");

app/views/admin/categories/destroy.js.erb
$("#category-<%= @category.id %>").remove();

app/views/admin/categories/edit.html.erb
<div class="row">
  <hr>
  <div class="col-md-4 col-md-offset-4">
    <h1 class="text-info text-center"><%= t "admin.category.update" %></h1>
    <br>
    <%= form_for [:admin, @category], class: "form form-inline" do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="form-group">
        <%= f.label t "name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <%= f.submit t("done"), class: "btn btn-primary pull-right" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="row">
  <div class="col-md-8">
    <table id="category_list_table" class="table table-hover table-bordered">
      <tbody>
        <tr>
          <th><%= t "admin.category.category" %></th>
          <th><%= t "admin.category.nums_of_question" %></th>
          <th><%= t "tool" %></th>
        </tr>
        <%= render @categories %>
      </tbody>
    </table>
  </div>
  <div class="col-md-4">
    <div>
      <%= form_for [:admin, @category], class: "form form-inline" do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <%= f.submit t("create"), class: "btn btn-primary pull-right" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/categories/show.html.erb
<br>
<div class="row">
  <div class="col-md-8">
    <hr>
    <table id="question_list_table" class="table table-hover table-bordered text-center">
      <tbody>
        <tr>
          <th class="text-center"><%= t "question" %></th>
          <th class="text-center"><%= t "tool" %></th>
        </tr>
        <% @questions.each do |question| %>
          <%= render "admin/questions/question", question: question %>
        <% end %>
      </tbody>  
    </table>
    <%= link_to t("admin.question.create_new_question"),
      new_admin_category_question_path(category_id: @category.id), class: "btn btn-primary" %>
  </div>
</div>