config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root "users#index"
    resources :users
    resources :categories do
      resources :questions
    end
    resources :exams
  end

  root "static_pages#home"
  devise_for :users, path: "", path_names: {
    sign_in: "login",
    sign_out: "logout"
  }
  resources :users, only: [:show, :edit, :update]
  resources :exams, only: [:index, :show, :create, :update]

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if user_signed_in? %>
      <%= link_to t("static_pages.test_app"), exams_path, id: "logo" %>
    <% else %>
      <%= link_to t("static_pages.test_app"), root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li><%= link_to t("admin.manage_user"), admin_users_path %></li>
            <li><%= link_to t("admin.manage_category"), admin_categories_path %></li>
            <li><%= link_to t("admin.manage_exam"), admin_exams_path %></li>
          <% end %>      
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "header.account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("header.profile"), current_user %></li>
              <li><%= link_to t("header.settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("log_out"), destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("header.login"), new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>